### ISSUE TITLE
IE11: nav logo is not rendering

### ISSUE THREAD

**Issue by jlpereira** [SpeciesFileGroup/taxonworks_homepage#15] opened 2017-06-14 23:10 UTC
It seems the logo is not displayed on the nav using IE11
![logo missing](https://user-images.githubusercontent.com/16530364/27158464-7e2bc500-513d-11e7-90cf-3d203b52aa2f.png)

**Comment by mjy** [comment] 2017-06-18 17:30
Also missing on FF dev.  Blocks #8.

**Comment by mjy** [comment] 2017-06-18 17:42
Duplicate of #8

**Closed by mjy** 2017-06-18 17:42 UTC
Labels: duplicate
